// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "9df3b682-62c3-4f0f-aeaf-e49d6ee5e191";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onPortionSizeChange();
void onServoChange();

float portionSize;
bool servo;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(portionSize, READWRITE, ON_CHANGE, onPortionSizeChange, 1);
  ArduinoCloud.addProperty(servo, READWRITE, ON_CHANGE, onServoChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
